### ISSUE TITLE
Compile error on latest version

### ISSUE THREAD

**Issue by github-aem** [mrk-its/esphome-canopen#17]
This is the error I am getting on all devices:
`src/esphome/components/canopen/canopen.cpp:449:6: error: redefinition of 'void esphome::canopen::CanopenComponent::add_entity(esphome::light::LightState*, uint32_t, int8_t)'
 void CanopenComponent::add_entity(esphome::light::LightState *light, uint32_t entity_id, int8_t tpdo) {
      ^~~~~~~~~~~~~~~~
In file included from src/esphome.h:21,
                 from src/esphome/components/canopen/canopen.cpp:2:
src/esphome/components/canopen/canopen.h:369:8: note: 'void esphome::canopen::CanopenComponent::add_entity(esphome::light::LightState*, uint32_t, int8_t)' previously defined here
   void add_entity(esphome::light::LightState *light, uint32_t entity_id, int8_t tpdo) {
        ^~~~~~~~~~
Compiling .pioenvs/m5dial/src/esphome/components/display/rect.cpp.o
*** [.pioenvs/m5dial/src/esphome/components/canopen/canopen.cpp.o] Error 1`
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

Is there any other information which can be helpful?

**Comment by mrk-its** [comment]
Thanks, I missed out 'light' platform in last refactor, I'm on it now.

**Comment by mrk-its** [comment]
It should be fixed now.
