### ISSUE TITLE
Can´t use together with fastled_clockless or neopixelbus

### ISSUE THREAD

**Issue by chefbauer** [mrk-its/esphome-canopen#25]
when compiling esphome-canopen together with fastled_clockless or neopixelbus, error:

Neopixel first error (some more all with micros() )
.piolibdeps/esphome-web-2ad030/NeoPixelBus/src/internal/Ws2801GenericMethod.h:64:33: error: call of overloaded 'micros()' is ambiguous

Fastled first error (some more all with micros() )
.piolibdeps/esphome-web-2ad030/FastLED/fastled_delay.h:21:19: error: call of overloaded 'micros()' is ambiguous

Both compile without esphome-canopen, last compile without fastled/neopixelbus

two against one! :)
maybe the others are faulty too...

esphome config:
light:
  - platform: neopixelbus
    variant: ws2812
    pin: GPIO4
    num_leds: 125
    method:
      type: esp32_rmt
    type: GRB
    id: "LED1"

or 
 - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO4
    num_leds: 125
    rgb_order: GRB
    id: "LED2"

thanks!

**Comment by chefbauer** [comment]
thank you for the fast fix!

**Comment by mrk-its** [comment]
Let me know if it works

**Comment by chefbauer** [comment]
both work now on arduino platform!

**Comment by mrk-its** [comment]
Great. Thanks for bug report, I think this issue  was affecting many other platforms too.
