### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by timota** [mrk-its/esphome-canopen#3]
Hi, 
your project looks awesome. 
Can you provide any examples how to communicate with your nodes via canbus (esphome config, etc...)? 

As an example: i have set of relays which are configured with your external component, lets call it actuator1 and your `can2mqtt` gateway which exposed entities to HA(which is great). I would like to configure another esp which will listen to changes from actuator1 and do some other work. Also, button will be attached to esp, and on press - it can send on/off to actuator1. In this case i would like not to use HA/Mqtt at all as it will add additional hopes/latency/complexity and use canbus as communication method. 

Thanks in advance.

**Comment by mrk-its** [comment]
Thanks!
I started to think about that recently: how to communicate directly between nodes. And I see two possible solutions:
* use canopen SDP client-server communication. Currently can2mqtt uses this protocol for sending commands to nodes, but nodes also can send commands to other nodes this way.
* use RPDO mapping definitions to 'wire' one object directory entry on one node with object directory entry on other node (this way we can 'wire' switch state with 'light' object state.

Currently I have working prototype of second approach and it looks promising.

**Comment by timota** [comment]
wow. nice. If you need a beta tester - im ready to test it for you. 

Thanks for your work.

**Comment by Tuckie** [comment]
Very excited by your work here! Glad to see you've been brainstorming ways to handle direct hardwired communication between ESPHome nodes without a single point of failure (e.g. modbus, ethernet).

I've been working on a project that I would like to have graceful degradation of functionality. 

For example:
* Home Assistant up - fancy touchscreens, remote control, advanced automations
* Home Assistant down - critical automations between devices, control via buttons, led indicators, etc
* Random node missing - raise error, but keep other nodes/functions up and running
* Bridge node down (assuming Can2MQTT can become Can2ESPHome someday) - let another ESPHome device automatically assume bridge responsibility.

This would allow me to keep things in a low energy state (HA off) while still keeping a lot of the "smarts" of the system.

**Comment by mrk-its** [comment]
> wow. nice. If you need a beta tester - im ready to test it for you.

@timota I've just commited support for RPDO mapping - this way data transmitted via TPDO message may be automatically mapped to node ObjectDictionary (for example switch state on one node to light on/off command on another node). I added additional `can-switch.yaml` example, toggling the light defined in `can-node.yaml`

**Comment by timota** [comment]
cool, going to try it today. I will let you know my findings. In mean time can you provide a bit more information on options and some explanations how it works ?

**Comment by mrk-its** [comment]
> In mean time can you provide a bit more information on options and some explanations how it works ?

I added some comments to tpdo / rpdo definitions in example `can-node.yaml` / `can-switch.yaml` files, I hope it will help.
I also recommend reading some general documentation about TPDO / RPDO in CANopen.

Very shortly: state of entities is stored in CANopen Object Dictionary. TPDO mapping defines how objects from Object Dictionary are mapped to TPDO CAN frames (there are up to 4 TPDOs for each CAN node, up to 8 bytes each), For example: https://github.com/mrk-its/esphome-canopen/blob/main/config/can-switch.yaml#L43 tells to map single byte of switch state to TPDO#0 frame. As it is first definition for tpdo#0 it will be stored with offset=0.

On the other hand RPDO allows to map part of received TPDO frame (from particular can node) to Object Dictionary. For any entity you can define list of RPDO mappings. Each such mapping needs to define `node_id`, `tpdo`, `offset` parameters, refering to  entity tpdo parameters on sibling node. When matching can frame is received proper frame part is mapped to current entity command, refered by `cmd` parameter.
