### ISSUE TITLE
[idea] heartbeat binary sensor

### ISSUE THREAD

**Issue by timota** [mrk-its/esphome-canopen#4]
It will be good to have a heartbeat binary sensor which will indicate if remote node (primary or secondary) has a connection.
Use case: 
- Primary lost connection to its secondary and via automations stops any operations related to that node, e.g. sprinkler controller with remote relays. 
- Secondary lost connection to its Primary and immediately stops all operations related to those entities that managed by that Primary, e.g. - sprinkler controller with remote relays, secondary lost connection to primary, both sides in jeopardy state, both stops all operations related to each other .

**Comment by mrk-its** [comment]
Sounds great! We should to be able to configure remote node id and heartbeat timeout.

**Comment by mrk-its** [comment]
Closing, as such sensor can be easily created after configuring heartbeat client, implemented in https://github.com/mrk-its/esphome-canopen/commit/286f96e86ca453bfb1378ba7f5a34c0d0a214092
