### ISSUE TITLE
Expose HB monitor callback function

### ISSUE THREAD

**Issue by timota** [mrk-its/esphome-canopen#6]
Please expose to esphome HB monitor callback function which called when timeout passes

https://discord.com/channels/1084113795447783554/1084113795447783557/1112458416351350825

**Comment by mrk-its** [comment]
usage:

```
canopen:
  on_hb_consumer_event:
    then:
      - lambda: |
          ESP_LOGW("canopen", "missed heartbeat from node %d", node_id);
```
